### ISSUE TITLE
Linking / copying a solver makes the "source" download stop working

### ISSUE THREAD

**Issue by quickbeam123** [StarExec/StarExec#307] opened 2021-06-18 18:12 UTC
Example:

https://www.starexec.org/starexec/secure/details/solver.jsp?id=31918

trying to download source of the above solver only yields a 61B corrupt zip file.

This solver is known to originate byl copying/linking from another one, where source download works.

**Comment by gg9192** [comment] 2023-07-06 19:38
drag the solver from one space to another and click link

**Comment by gg9192** [comment] 2023-07-07 19:25
Hello sir,

I hope this finds you well. My name is Alex Guo, and I am the student engineer assigned to work on this ticket. I wanted to inform you about my approach to managing and updating tickets for better collaboration and progress tracking.

Typically, I make frequent updates and comments on tickets to ensure that I have a clear understanding of the tasks at hand and to provide a space for Dr. Stump to review the progress made. However, I understand that this may result in a flood of email notifications for you. Therefore, I would like to discuss with you if this poses any inconvenience or issues on your end.

I value effective communication and collaboration, and I want to ensure that our ticket management process is efficient for both of us. If you have any concerns or suggestions regarding this matter, please let me know, and I will be more than happy to accommodate your preferences.

Thank you for your understanding.

Best regards,
Alex Guo

**Comment by gg9192** [comment] 2023-07-07 19:48
Here are the investigative notes:
Reproducing the error: 
1. find a solver that needs to be built
2. upload to starexec
3. COPY the solver from one space to another by dragging it into the space and clicking copy. [Note that this error only happens when you copy. ](https://iowa-my.sharepoint.com/:v:/g/personal/aguo2_uiowa_edu/EbOPKDBNeURGgDaGiNifiN8B3SF3TMqCGHSIAzxHRN6cvQ?e=evudXa)
4. trying to download the copied solver yeilds a corrupted zip

**Comment by gg9192** [comment] 2023-07-07 20:25
What is the problem? When you upload a solver, we store it in our data directory. When you copy the solver, tomcat goes and creates a new directory and copies the solver in there. On our dev environment, the path is: /home/starexec/starexec_aguo2/data_dir/Solvers/1. When we have a solver that needs to be built, we have one directory for the src code and another for the actual solver. These are stored in the form {$timestamp} and {$timestamp}_src Unfortunatly, when the solver gets copied, only the solver gets copied and not the src code.  Please observe the following output: 
---------------------------------------------------------------------------------------------------------------------
aguo2@stardev1 build]$ ls
20230707-14.40.01.555  20230707-14.40.01.555_src  20230707-14.45.08.638  20230707-14.52.35.356  20230707-15.13.09.586
---------------------------------------------------------------------------------------------------------------------
The solvers that have only {$timestamp} and not {$timestamp}_src are the copied solvers. We need to make sure when we copy solver, we copy the src as well. Then we need to make sure that when the user downloads the solver, our db has the right directory.

**Comment by gg9192** [comment] 2023-07-07 23:32
Our code is looking for a folder with the _src as stated in the above comment. Clearly, the code does not make the directory with the _src added. Because of this, we can't find the solver's src code and we output something strange. I know that the code responsible for the downloads isn't broken. If it was, you wouldn't be able to get the source code whatsoever

**Comment by gg9192** [comment] 2023-07-08 17:17
https://github.com/StarExec/StarExec/pull/360

**Closed as completed by gg9192** 2023-07-08 17:17 UTC
